version: '{build}'
shallow_clone: true

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: cygwin

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% --installdeps -n --with-develop --with-recommends .'

build: off

test_script:
  - 'prove -l t t/mojo t/mojolicious'
