pull_request_rules:
  - name: automatic merge
    conditions:
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - label!=work in progress
      - base=main
    actions:
      merge:
        method: merge
  - name: remove outdated reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? ğŸ™
