name: Rebuild Website
on:
  push:
    branches:
      - master
jobs:
  rebuild_website:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website workflow
        run: |
          curl \
            -X POST \
            -u "${{ secrets.WORKFLOW_DISPATCH_USERINFO }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            --data '{"ref": "master"}' \
            https://api.github.com/repos/mojolicious/mojolicious.org/actions/workflows/docker-publish.yml/dispatches
